name: Deployment Royal

on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment: exzork vps
    runs-on: ubuntu-latest
    steps:
      - name : Checkout
        uses: actions/checkout@v2
      - name : Deploy Docker Using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/project/royal-challenge
            git pull
            docker-compose down
            docker-compose build
            docker-compose up -d